name: Generate CHANGELOG.md
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
        
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_messsage: "doc: updated CHANGELOG.md"
          branch: main
          repository: .
          commit_user_name: "Jimmy Briggs"
          commit_user_email: jimmy.briggs@jimbrig.com
          commit_author: "Jimmy Briggs"
