name: Generate CHANGELOG.md
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
        
      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit Changelog
        run: |
          # Stage the file, commit and push
          git add CHANGELOG.md
          git commit -m "doc: updated CHANGELOG.md"
          git push origin master 
      
